#!/usr/bin/env python3
"""Writes, or checks, the licence notices of the Rust crates the `ragondin`
binary links: `bin/ragondin/third-party-notices-rust.txt`.

The binary statically links its dependency closure, and the MIT, BSD and
Apache-2.0 terms most of those crates carry require their copyright and licence
notices to accompany a redistributed binary. The binary embeds this file and
prints it (`ragondin --notices`), and `ragondin ui` serves it at
`/third-party-notices-rust.txt`, beside the UI's own notices
(`bin/ragondin/ARCHITECTURE.md` § The licence notices of the Rust crates).

**What it reads.** Only what the toolchain already gives: `cargo metadata
--all-features --locked`, with no platform filter, and the files of each
crate's own source directory, which that command has already unpacked. No
dependency and no tool: the repository's Python tooling carries none, by
decision.

**What it lists.** Every package reached from the `ragondin` package over
**normal** dependency edges, transitively, with every feature on and for every
platform. That is a superset of what any one build links, so one file serves
every build, and it is the same on every machine. Dev-dependencies are never
linked. Build-dependencies run at build time and are not linked either, so
neither is listed. A proc-macro reached over a normal edge is listed, which
errs on the side the licences ask for. A package whose manifest lies under the
workspace root and that has no registry source is this repository's own
(Apache-2.0, stated in the header) and is not listed. A path dependency from
outside the repository is listed like any other.

**What a crate's entry holds.** Its name, version and licence expression, and
every file it ships at its root whose name says it is a licence or a notice:
`LICENSE`, `LICENCE`, `COPYING` or `NOTICE`, in any case, bare or with a `.` or
`-` suffix (`LICENSE-MIT`, `LICENSE.txt`). A dual-licensed crate ships both
texts, so both are reproduced. Each text is normalised to `\\n` line endings
and one final newline, and written once, under a label taken from its
SHA-256, however many crates ship it.

**A crate that ships no licence file.** It gets the standard text of every
alternative of its licence expression that `deny.toml`'s `[licenses] allow`
admits and `scripts/licence-texts/` holds, and its entry says that it ships
none and names the authors its manifest gives as the copyright holders,
saying, under MIT, that they fill the standard text's placeholder. An
alternative that is compound (`AND`, `WITH`) is not used. When no alternative
qualifies, generation fails and names the crate: the remedy is a reviewed text
under `scripts/licence-texts/`, never a guess.

`--check` regenerates in memory and compares with the committed file. It
names every linked crate that has no entry there, and otherwise reports the
file stale. It writes nothing.

Run via `just gen-rust-notices` and `just check-rust-notices`; tested by
`just test-gen-rust-notices`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tomllib

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join("bin", "ragondin", "third-party-notices-rust.txt")
TEXTS = os.path.join("scripts", "licence-texts")
BINARY = "ragondin"

LICENCE_FILE = re.compile(r"^(licen[cs]e|copying|notice)([-.][\w.-]+)?$", re.IGNORECASE)
RULE = "=" * 80
THIN = "-" * 80

HEADER = """\
Third-party notices of the ragondin binary: the Rust crates it links

ragondin is licensed under Apache-2.0 (the LICENSE file of its repository).
The binary links the Rust crates below, each distributed under the licence
reproduced with it. The list is every crate from outside the repository in
the dependency graph of the `ragondin` package, with all of its features on
and for every platform, so it covers every build of the binary. Crates used
only at build time are not linked and are not listed.

Each crate names the licence texts it ships, by label; the texts follow the
list, each written once. A crate that ships no licence file is said to, and
the standard text of its declared licence is given, with the authors its
manifest names as the copyright holders.

The UI that `ragondin ui` serves has notices of its own, served at
/third-party-notices.txt.

Generated by scripts/gen-rust-notices.py from `cargo metadata`. Do not edit.
"""


class Refused(Exception):
    """A notice that cannot be written."""


def metadata(root: str, path: str | None) -> dict:
    if path is not None:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    completed = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--all-features", "--locked"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise Refused(f"`cargo metadata` failed:\n{completed.stderr}")
    return json.loads(completed.stdout)


def allowed(root: str) -> set[str]:
    with open(os.path.join(root, "deny.toml"), "rb") as handle:
        return set(tomllib.load(handle)["licenses"]["allow"])


def linked(document: dict) -> list[dict]:
    """The third-party packages reached from the binary over normal edges."""
    packages = {package["id"]: package for package in document["packages"]}
    deps = {node["id"]: node["deps"] for node in document["resolve"]["nodes"]}
    roots = [
        member for member in document["workspace_members"] if packages[member]["name"] == BINARY
    ]
    if len(roots) != 1:
        raise Refused(f"expected one workspace member named {BINARY}, found {len(roots)}")
    workspace = os.path.realpath(document["workspace_root"])
    seen: set[str] = set()
    stack = list(roots)
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in deps.get(current, []):
            if any(kind["kind"] is None for kind in dep["dep_kinds"]):
                stack.append(dep["pkg"])

    def ours(package: dict) -> bool:
        if package["source"] is not None:
            return False
        manifest = os.path.realpath(package["manifest_path"])
        return os.path.commonpath([manifest, workspace]) == workspace

    found = [packages[key] for key in seen if not ours(packages[key])]
    return sorted(found, key=lambda package: (package["name"], package["version"]))


def normalised(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip() + "\n"


def read_text(path: str, who: str) -> str:
    try:
        with open(path, encoding="utf-8", newline="") as handle:
            return normalised(handle.read())
    except UnicodeDecodeError as error:
        raise Refused(f"{who}: {os.path.basename(path)} is not UTF-8 ({error})") from error


def label(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def alternatives(expression: str) -> list[str]:
    """The top-level `OR` alternatives of a licence expression, `/` read as the
    old spelling of `OR`, each stripped of its outer parentheses."""
    spaced = expression.replace("/", " OR ").replace("(", " ( ").replace(")", " ) ")
    tokens = spaced.split()
    found: list[list[str]] = [[]]
    depth = 0
    for token in tokens:
        if token == "(":
            depth += 1
        elif token == ")":
            depth -= 1
        if token == "OR" and depth == 0:
            found.append([])
        else:
            found[-1].append(token)
    result = []
    for alternative in found:
        while len(alternative) >= 2 and alternative[0] == "(" and alternative[-1] == ")":
            alternative = alternative[1:-1]
        result.append(" ".join(alternative))
    return result


def entry(package: dict, root: str, allow: set[str], texts: dict[str, str]) -> list[str]:
    """The lines of one crate's entry; its texts are added to `texts`."""
    who = f"{package['name']} {package['version']}"
    directory = os.path.dirname(package["manifest_path"])
    files = sorted(
        name
        for name in os.listdir(directory)
        if LICENCE_FILE.match(name) and os.path.isfile(os.path.join(directory, name))
    )
    shipped = [(name, os.path.join(directory, name)) for name in files]
    if package.get("license_file"):
        named = os.path.join(directory, package["license_file"])
        if os.path.isfile(named) and all(path != named for _, path in shipped):
            shipped.append((package["license_file"].replace(os.sep, "/"), named))
    expression = package.get("license") or "none declared"
    lines = [RULE, who, f"Licence: {expression}"]
    if shipped:
        for name, path in shipped:
            text = read_text(path, who)
            texts[label(text)] = text
            lines.append(f"{name}: text {label(text)}")
        return lines

    standard = []
    if package.get("license"):
        for alternative in alternatives(package["license"]):
            path = os.path.join(root, TEXTS, f"{alternative}.txt")
            if alternative in allow and os.path.isfile(path):
                standard.append((alternative, read_text(path, alternative)))
    if not standard:
        raise Refused(
            f"{who} ships no licence file, and no alternative of its licence "
            f"({expression}) is both allowed by deny.toml and held under {TEXTS}/"
        )
    authors = ", ".join(package.get("authors") or []) or "none named"
    lines.append("Ships no licence file; the standard text of its licence applies.")
    lines.append(f"Copyright holders, as its manifest names its authors: {authors}")
    if any(name == "MIT" for name, _ in standard):
        lines.append("MIT's <year> <copyright holders> placeholder is filled by the line above.")
    for name, text in standard:
        texts[label(text)] = text
        lines.append(f"{name} (standard text): text {label(text)}")
    return lines


def render(packages: list[dict], root: str, allow: set[str]) -> str:
    texts: dict[str, str] = {}
    blocks: list[str] = []
    refused: list[str] = []
    for package in packages:
        try:
            blocks.append("\n".join(entry(package, root, allow, texts)))
        except Refused as error:
            refused.append(str(error))
    if refused:
        raise Refused("The Rust crates' notices cannot be written:\n  " + "\n  ".join(refused))
    parts = [HEADER, f"{len(packages)} crates", "", *[block + "\n" for block in blocks]]
    parts.append(f"{RULE}\n{RULE}\nThe licence texts, by label\n")
    for key in sorted(texts):
        parts.append(f"{RULE}\nText {key}\n{THIN}\n{texts[key]}")
    return "\n".join(parts).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="compare, write nothing")
    parser.add_argument("--root", default=os.path.dirname(SCRIPTS_DIR), help=argparse.SUPPRESS)
    parser.add_argument("--metadata", help=argparse.SUPPRESS)
    arguments = parser.parse_args()
    root = arguments.root
    output = os.path.join(root, OUTPUT)
    try:
        packages = linked(metadata(root, arguments.metadata))
        text = render(packages, root, allowed(root))
    except Refused as error:
        print(error, file=sys.stderr)
        return 1

    if not arguments.check:
        with open(output, "w", encoding="utf-8", newline="") as handle:
            handle.write(text)
        print(f"wrote {OUTPUT}: {len(packages)} crates")
        return 0

    try:
        with open(output, encoding="utf-8", newline="") as handle:
            committed = handle.read()
    except FileNotFoundError:
        committed = ""
    if committed == text:
        print(f"{OUTPUT} is current: every linked crate has its notice ({len(packages)} crates).")
        return 0
    missing = [
        f"{package['name']} {package['version']}"
        for package in packages
        if f"\n{package['name']} {package['version']}\n" not in committed
    ]
    for crate in missing:
        print(f"{crate}: linked, and no notice in {OUTPUT}", file=sys.stderr)
    if not missing:
        print(f"{OUTPUT} is stale: its texts or entries differ from what is linked.", file=sys.stderr)
    print("Run `just gen-rust-notices` and commit the result.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
